"""add numeric id to nodes

Revision ID: 20251223_add_numeric_id_to_nodes
Revises: 20251222_create_background_job_history
Create Date: 2025-12-23
"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "20251223_add_numeric_id_to_nodes"
down_revision = "20251222_create_background_job_history"
branch_labels = None
depends_on = None


def upgrade():
    op.execute("ALTER TABLE nodes RENAME COLUMN id TO alt_id")
    op.execute(
        "ALTER TABLE nodes ADD COLUMN id BIGINT GENERATED BY DEFAULT AS IDENTITY"
    )
    op.execute("UPDATE nodes SET id = nextval('nodes_id_seq')")
    op.create_index("ux_nodes_id", "nodes", ["id"], unique=True)


def downgrade():
    op.drop_index("ux_nodes_id", table_name="nodes")
    op.execute("ALTER TABLE nodes DROP COLUMN id")
    op.execute("ALTER TABLE nodes RENAME COLUMN alt_id TO id")
