openapi: 3.0.3
info:
  title: Notifications API
  version: 1.0.0
paths:
  /v1/notifications/send:
    post:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object

