openapi: 3.1.0
info:
  title: Workspace API v1
  version: "1.0"
paths:
  /v1/nodes/{alt_id}:
    get:
      summary: Get node by alt_id
      parameters:
        - in: path
          name: alt_id
          required: true
          schema:
            type: string
            format: uuid
      responses:
        "200":
          description: Node details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Node'
components:
  schemas:
    Node:
      type: object
      properties:
        altId:
          type: string
          format: uuid
        title:
          type: string
