openapi: 3.1.0
info:
  title: Workspace API v2
  version: "2.0"
paths:
  /v2/nodes/{id}:
    get:
      summary: Get node by id
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: Node details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Node'
components:
  schemas:
    Node:
      type: object
      properties:
        id:
          type: integer
        altId:
          type: string
          format: uuid
          deprecated: true
        title:
          type: string
