repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.10
    hooks:
      - id: ruff
        args: [--fix]
        language_version: python3.11
  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
        language_version: python3.11
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.17.1
    hooks:
      - id: mypy
        args: ["apps/backend/app"]
        language_version: python3.11
  - repo: local
    hooks:
      - id: eslint
        name: eslint
        entry: bash -c 'cd admin-frontend && npx --no-install eslint . --max-warnings=0'
        language: system
        files: ^admin-frontend/
        pass_filenames: false
      - id: tsc
        name: tsc
        entry: bash -c 'cd admin-frontend && npx --no-install tsc --noEmit'
        language: system
        files: ^admin-frontend/
        pass_filenames: false
