[tool.black]
line-length = 88
extend-exclude = "apps/admin"

[tool.isort]
profile = "black"
line_length = 88
src_paths = ["apps/backend"]

[tool.ruff]
line-length = 88
target-version = "py311"
src = ["apps/backend"]
extend-exclude = ["apps/admin"]


[tool.ruff.lint]
select = ["E", "F", "W", "B", "UP", "I"]
ignore = ["D"]

[tool.ruff.lint.per-file-ignores]
"apps/backend/alembic/versions/*.py" = ["ALL"]

[tool.mypy]
explicit_package_bases = true
