[tool.black]
line-length = 100
extend-exclude = "apps/admin"

[tool.isort]
profile = "black"
line_length = 100
src_paths = ["apps/backend"]

[tool.ruff]
line-length = 100
target-version = "py311"
src = ["apps/backend"]
extend-exclude = ["apps/admin"]


[tool.ruff.lint]
select = ["E", "F", "W", "B", "UP", "I"]
# Project style: allow FastAPI Body(...) defaults, long lines in docs/comments,
# and postpone-import patterns where needed.
ignore = ["D", "E501", "B008", "E402"]

[tool.ruff.lint.per-file-ignores]
"apps/backend/migrations/versions/*.py" = ["ALL"]

[tool.mypy]
scripts_are_modules = true
python_version = "3.11"
explicit_package_bases = true
follow_imports = "skip"
mypy_path = ["apps/backend"]
ignore_missing_imports = false
disable_error_code = ["import-untyped"]

# ВАЖНО: укажи, ЧТО проверять, вместо "packages = …"
files = ["apps/backend/domains/platform/notifications/application", "apps/backend/domains/platform/notifications/adapters", "apps/backend/domains/platform/notifications/tests"]

# Отрежем мусор и виртуальные окружения
exclude = "(^|/)(build|dist|.venv|venv|.mypy_cache|.pytest_cache)/|apps/backend/__init__\\.py"

[[tool.mypy.overrides]]
module = ["yaml", "requests"]
ignore_missing_imports = true

