[tool.black]
line-length = 100
extend-exclude = "apps/admin"

[tool.isort]
profile = "black"
line_length = 100
src_paths = ["apps/backend"]

[tool.ruff]
line-length = 100
target-version = "py311"
src = ["apps/backend"]
extend-exclude = ["apps/admin"]


[tool.ruff.lint]
select = ["E", "F", "W", "B", "UP", "I"]
ignore = ["D"]

[tool.ruff.lint.per-file-ignores]
"apps/backend/alembic/versions/*.py" = ["ALL"]

[tool.mypy]
python_version = "3.11"
explicit_package_bases = true
packages = ["apps.backend.app"]
exclude = "(^|/)(build|dist|.venv|venv)/"
