[tool.black]
line-length = 100
extend-exclude = "apps/admin"

[tool.isort]
profile = "black"
line_length = 100
src_paths = ["apps/backend"]

[tool.ruff]
line-length = 100
target-version = "py311"
src = ["apps/backend"]
extend-exclude = ["apps/admin"]


[tool.ruff.lint]
select = ["E", "F", "W", "B", "UP", "I"]
# Project style: allow FastAPI Body(...) defaults, long lines in docs/comments,
# and postpone-import patterns where needed.
ignore = ["D", "E501", "B008", "E402"]

[tool.ruff.lint.per-file-ignores]
"apps/backend/alembic/versions/*.py" = ["ALL"]

[tool.mypy]
python_version = "3.11"
explicit_package_bases = true
mypy_path = "."
ignore_missing_imports = false
disable_error_code = ["import-untyped"]

# ВАЖНО: укажи, ЧТО проверять, вместо "packages = …"
files = [
  "apps/backend/app",
]

# Отрежем мусор и виртуальные окружения
exclude = "(^|/)(build|dist|.venv|venv|.mypy_cache|.pytest_cache)/"

[[tool.mypy.overrides]]
module = ["yaml", "requests"]
ignore_missing_imports = true
