[tool.black]
line-length = 100
extend-exclude = "apps/admin"

[tool.isort]
profile = "black"
line_length = 100
src_paths = ["apps/backend"]

[tool.ruff]
line-length = 100
target-version = "py311"
src = ["apps/backend"]
extend-exclude = ["apps/admin"]


[tool.ruff.lint]
select = ["E", "F", "W", "B", "UP", "I"]
ignore = ["D"]

[tool.ruff.lint.per-file-ignores]
"apps/backend/alembic/versions/*.py" = ["ALL"]

[tool.mypy]
python_version = "3.11"
explicit_package_bases = true

# ВАЖНО: укажи, ЧТО проверять, вместо "packages = …"
files = [
  "apps/backend/app",
  "apps/backend/tests",  # если хочешь типизировать тесты; иначе строку убери
]

# Отрежем мусор и виртуальные окружения
exclude = "(^|/)(build|dist|.venv|venv|.mypy_cache|.pytest_cache)/"
