version: "3.8"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: app
    ports: ["5432:5432"]
  redis:
    image: redis:7
    ports: ["6379:6379"]

  events-worker:
    image: python:3.11-slim
    working_dir: /app
    volumes:
      - ../../..:/app
    environment:
      - PYTHONPATH=/app
      - APP_EVENT_TOPICS=${APP_EVENT_TOPICS:-profile.updated.v1}
    command: ["python","-m","apps.backend.infra.events_worker"]
    depends_on:
      - redis
