export * from './billing';
export * from './ai';
export * from './flags';
export * from './integrations';
export * from './system';
export * from './audit';
export * from './siteEditor';

import {
  fetchBillingOverview,
  fetchBillingKpi,
  fetchBillingProviders,
  saveBillingProvider,
  deleteBillingProvider,
  fetchBillingTransactions,
  fetchBillingContracts,
  saveBillingContract,
  deleteBillingContract,
  fetchBillingContractEvents,
  fetchBillingCryptoConfig,
  updateBillingCryptoConfig,
  fetchBillingMetrics,
  fetchBillingPlans,
  saveBillingPlan,
  deleteBillingPlan,
  updateBillingPlanLimits,
  fetchBillingPlanHistory,
  fetchBillingOverviewPayouts,
} from './billing';
import {
  fetchManagementAiModels,
  saveManagementAiModel,
  deleteManagementAiModel,
  fetchManagementAiProviders,
  saveManagementAiProvider,
  fetchManagementAiFallbacks,
  createManagementAiFallback,
  deleteManagementAiFallback,
  fetchManagementAiSummary,
  runManagementAiPlayground,
} from './ai';
import {
  fetchFeatureFlags,
  saveFeatureFlag,
  deleteFeatureFlag,
  searchFeatureFlagUsers,
} from './flags';
import {
  fetchIntegrationsOverview,
  fetchManagementConfig,
  sendNotificationTest,
} from './integrations';
import { fetchSystemConfig, fetchSystemOverview } from './system';
import {
  fetchAuditEvents,
  fetchAuditUsers,
} from './audit';
import {
  fetchSitePages,
  fetchSitePage,
  fetchSitePageDraft,
  createSitePage,
  updateSitePage,
  deleteSitePage,
  saveSitePageDraft,
  validateSitePageDraft,
  diffSitePageDraft,
  previewSitePage,
  previewSiteBlock,
  fetchSitePageHistory,
  fetchSitePageVersion,
  restoreSitePageVersion,
  fetchSiteAudit,
} from './siteEditor';

export const managementApi = {
  fetchBillingOverview,
  fetchBillingKpi,
  fetchBillingProviders,
  saveBillingProvider,
  deleteBillingProvider,
  fetchBillingTransactions,
  fetchBillingContracts,
  saveBillingContract,
  deleteBillingContract,
  fetchBillingContractEvents,
  fetchBillingCryptoConfig,
  updateBillingCryptoConfig,
  fetchBillingMetrics,
  fetchBillingPlans,
  saveBillingPlan,
  deleteBillingPlan,
  updateBillingPlanLimits,
  fetchBillingPlanHistory,
  fetchBillingOverviewPayouts,
  fetchManagementAiModels,
  saveManagementAiModel,
  deleteManagementAiModel,
  fetchManagementAiProviders,
  saveManagementAiProvider,
  fetchManagementAiFallbacks,
  createManagementAiFallback,
  deleteManagementAiFallback,
  fetchManagementAiSummary,
  runManagementAiPlayground,
  fetchFeatureFlags,
  saveFeatureFlag,
  deleteFeatureFlag,
  searchFeatureFlagUsers,
  fetchIntegrationsOverview,
  fetchManagementConfig,
  sendNotificationTest,
  fetchSystemOverview,
  fetchSystemConfig,
  fetchAuditEvents,
  fetchAuditUsers,
  fetchSitePages,
  fetchSitePage,
  fetchSitePageDraft,
  createSitePage,
  updateSitePage,
  deleteSitePage,
  saveSitePageDraft,
  validateSitePageDraft,
  diffSitePageDraft,
  previewSitePage,
  previewSiteBlock,
  fetchSitePageHistory,
  fetchSitePageVersion,
  restoreSitePageVersion,
  fetchSiteAudit,
};
