apiVersion: v1
kind: ConfigMap
metadata:
  name: <your-domain>-config
data:
  LOG_LEVEL: INFO

# ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: <your-domain>
spec:
  replicas: 1
  selector:
    matchLabels: { app: <your-domain> }
  template:
    metadata:
      labels: { app: <your-domain> }
    spec:
      containers:
        - name: app
          image: your.registry/<your-domain>:latest
          envFrom:
            - configMapRef: { name: <your-domain>-config }

