// This file is auto-generated by scripts/generate_front_cors.ts
export const corsConfig = {
  allowOrigins: ["https://yourdomain.com", "https://app.yourdomain.com"],
  allowCredentials: true,
  allowMethods: ["GET", "POST", "PUT", "DELETE", "OPTIONS", "PATCH"],
  allowHeaders: ["Authorization", "Content-Type", "X-CSRF-Token", "X-CSRFToken", "X-Requested-With", "X-Workspace-Id", "Workspace-Id", "X-Feature-Flags", "X-Preview-Token", "X-Request-ID", "X-BlockSketch-Workspace-Id", "X-Client-Platform", "X-XSRF-Token", "X-Client-Language", "X-Client-Version", "X-User-Timezone"],
} as const;
