openapi: 3.0.3
info:
  title: Events Admin API
  version: 1.0.0
paths:
  /v1/events/stats/{topic}:
    get:
      parameters:
        - in: path
          name: topic
          required: true
          schema: { type: string }
        - in: query
          name: group
          schema: { type: string }
      responses:
        '200': { description: OK }

