openapi: 3.0.3
info:
  title: Users API (domain slice)
  version: 0.1.0
paths:
  /users/me:
    get:
      operationId: users_getMe
      responses: { "200": { description: ok } }
    patch:
      operationId: users_patchMe
      responses: { "200": { description: ok } }
