name: Nightly
on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch: {}

jobs:
  nightly:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install backend dependencies
        working-directory: apps/backend
        run: |
          python -m pip install --upgrade pip
          python -m pip install -e .
          python -m pip install -r requirements.txt
          python -m pip install ruff mypy pytest

      - name: Ruff
        working-directory: apps/backend
        run: python -m ruff check . --config pyproject.toml

      - name: Mypy
        working-directory: apps/backend
        run: python -m mypy . --config-file pyproject.toml

      - name: Slow tests
        working-directory: apps/backend
        run: python -m pytest -c pytest.ini -m slow --durations=20
