name: Nightly
on:
  schedule: [{ cron: "0 2 * * *" }]
  workflow_dispatch: {}
jobs:
  slow-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.11", cache: "pip" }
      - run: make setup
      - run: pytest -m slow apps/backendDDD --durations=20 || true
