name: CI
on:
  pull_request:
    paths:
      - "apps/**"
      - "pyproject.toml"
      - "requirements*.txt"
  push:
    branches: [main]
concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  gate:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
      - name: Ensure legacy directory is empty
        run: scripts/check_no_legacy_files.sh
      - uses: actions/setup-python@v5
        with: { python-version: "3.11", cache: "pip" }
      - name: Install
        run: make setup
      - name: Lint
        run: make lint
      - name: Types
        run: make type
      - name: Unit tests
        run: make unit
