name: CI

on:
  push:
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          pip install pytest import-linter pyyaml jsonschema ruff mypy redis sqlalchemy pydantic-settings PyJWT

      - name: Ruff (lint)
        run: |
          ruff check apps/backendDDD --config apps/backendDDD/pyproject.toml

      - name: Mypy (type check)
        run: |
          mypy apps/backendDDD --config-file apps/backendDDD/pyproject.toml

      - name: Validate schemas
        run: |
          bash apps/backendDDD/infra/ci/schemas-validate.sh

      - name: Check import boundaries
        run: |
          python apps/backendDDD/infra/ci/gen_import_rules.py > importlinter.ini
          lint-imports -c importlinter.ini

      - name: Run tests
        env:
          PYTHONPATH: apps/backendDDD
        run: |
          python -m pytest -q apps/backendDDD/domains
          python -m pytest -q apps/backendDDD/app/tests
