name: Docs

on:
  push:
    branches: [main]
    paths:
      - 'docs/**'
  pull_request:
    paths:
      - 'docs/**'

jobs:
  generate-openapi:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install backend dependencies
        working-directory: apps/backend
        run: |
          python -m pip install --upgrade pip
          python -m pip install -e .
          python -m pip install -r requirements.txt

      - name: Generate OpenAPI schema
        working-directory: apps/backend
        run: |
          python - <<'PYTHON'
          from fastapi.openapi.utils import get_openapi
          from apps.backend.app.api_gateway.main import app
          import json, pathlib

          schema = get_openapi(
              title='API',
              version='1.0.0',
              description='',
              routes=app.routes,
          )
          out = pathlib.Path('../docs/openapi')
          out.mkdir(parents=True, exist_ok=True)
          out.joinpath('openapi.json').write_text(json.dumps(schema, indent=2, ensure_ascii=False))
          PYTHON
