name: Reconcile node items

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  reconcile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Reconcile node items
        env:
          DATABASE__HOST: ${{ secrets.DATABASE_HOST }}
          DATABASE__PORT: ${{ secrets.DATABASE_PORT }}
          DATABASE__NAME: ${{ secrets.DATABASE_NAME }}
          DATABASE__USERNAME: ${{ secrets.DATABASE_USER }}
          DATABASE__PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
          REDIS_URL: ${{ secrets.REDIS_URL }}
        run: python scripts/reconcile_node_items.py
